### ISSUE TITLE
Reset back to my setup

### ISSUE THREAD

**Issue by nasr18** [keiththomps/dotfiles#1]
How do i reset back to my previous setup? @keiththomps

**Comment by keiththomps** [comment]
Were you relying on a previous version of my dotfiles? If so, I would suggest forking the repository to your Github account, changing your local repository to point to your repo using `git remote set-url origin YOUR_GIT_REPO_URL`, going through the commits to find the SHA of the commit that you want to reset to and then use the command:

```
git reset --hard $SHA
```

From there you can push that up to your repository and that will be the current state of *your* dotfiles repository by using this command:

```
git push --force origin master
```
